# Generated by Django 5.1.4 on 2025-11-02 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kanji',
            fields=[
                ('kanji_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('character', models.CharField(max_length=10)),
                ('onyomi', models.CharField(blank=True, max_length=100, null=True)),
                ('kunyomi', models.CharField(blank=True, max_length=100, null=True)),
                ('meaning', models.TextField(blank=True, null=True)),
                ('strokes', models.IntegerField(blank=True, null=True)),
                ('jlpt_level', models.CharField(blank=True, max_length=5, null=True)),
                ('example', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('admin', 'Admin')], default='student', max_length=20)),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('streak', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('failed_login_attempts', models.IntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('level', models.CharField(blank=True, max_length=5, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('otp_code_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_codes', to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='ListeningLesson',
            fields=[
                ('listening_lesson_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True, null=True)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('jlpt_level', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skill')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='FlashcardSet',
            fields=[
                ('flashcard_set_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_sets', to='core.user')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=255)),
                ('reading', models.CharField(blank=True, max_length=255, null=True)),
                ('meaning', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('example', models.TextField(blank=True, null=True)),
                ('jlpt_level', models.CharField(blank=True, max_length=5, null=True)),
                ('pronunciation_url', models.URLField(blank=True, null=True)),
                ('kanji', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='words', to='core.kanji')),
            ],
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('flashcard_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flashcard_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='core.flashcardset')),
                ('word', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcards', to='core.word')),
            ],
        ),
    ]
