# Generated by Django 5.1.4 on 2025-11-02 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='ChatbotMessage',
            fields=[
                ('chatbot_message_id', models.AutoField(primary_key=True, serialize=False)),
                ('conversation_id', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=20)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('message_type', models.CharField(default='text', max_length=50)),
                ('attachment_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'chatbot_messages',
            },
        ),
        migrations.CreateModel(
            name='GrammarLesson',
            fields=[
                ('grammar_lesson_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('explanation', models.TextField()),
                ('jlpt_level', models.CharField(max_length=10)),
                ('example_sentence', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skill')),
            ],
        ),
        migrations.CreateModel(
            name='MockTest',
            fields=[
                ('mock_test_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('jlpt_level', models.CharField(max_length=5)),
                ('description', models.TextField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'mock_tests',
            },
        ),
        migrations.CreateModel(
            name='MockTestAttempt',
            fields=[
                ('mock_test_attempt_id', models.AutoField(primary_key=True, serialize=False)),
                ('jlpt_level', models.CharField(max_length=5)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.FloatField(default=0)),
                ('status', models.CharField(default='in_progress', max_length=20)),
                ('time_taken_seconds', models.IntegerField(default=0)),
                ('responses', models.JSONField(default=dict)),
                ('mock_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mocktest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'mock_test_attempts',
            },
        ),
        migrations.CreateModel(
            name='ReadingLesson',
            fields=[
                ('reading_lesson_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('passage', models.TextField()),
                ('jlpt_level', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skill')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('section_title', models.CharField(blank=True, max_length=255, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('question_type', models.CharField(max_length=50)),
                ('question_text', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(max_length=10)),
                ('points', models.FloatField(default=1)),
                ('media_url', models.CharField(blank=True, max_length=255, null=True)),
                ('grammar_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.grammarlesson')),
                ('listening_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.listeninglesson')),
                ('mock_test', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mocktest')),
                ('reading_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.readinglesson')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='VocabLesson',
            fields=[
                ('vocab_lesson_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('jlpt_level', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.user')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skill')),
            ],
        ),
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('user_lesson_progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(default='in_progress', max_length=20)),
                ('completion_percent', models.FloatField(default=0)),
                ('score', models.FloatField(default=0)),
                ('last_accessed', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grammar_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.grammarlesson')),
                ('listening_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.listeninglesson')),
                ('reading_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.readinglesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
                ('vocab_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.vocablesson')),
            ],
            options={
                'db_table': 'user_lesson_progress',
            },
        ),
        migrations.CreateModel(
            name='JLPTProgress',
            fields=[
                ('jlpt_progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('jlpt_level', models.CharField(max_length=5)),
                ('total_tests_taken', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('best_score', models.FloatField(default=0)),
                ('last_test_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'jlpt_progress',
                'unique_together': {('user', 'jlpt_level')},
            },
        ),
        migrations.CreateModel(
            name='UserSkillProgress',
            fields=[
                ('user_skill_progress_id', models.AutoField(primary_key=True, serialize=False)),
                ('jlpt_level', models.CharField(max_length=5)),
                ('completion_percent', models.FloatField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('current_level', models.CharField(blank=True, max_length=5, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.user')),
            ],
            options={
                'db_table': 'user_skill_progress',
                'unique_together': {('user', 'skill', 'jlpt_level')},
            },
        ),
    ]
